MSG_HEADER_LABEL = 'HEADER'
MSG_HEADER_REQUEST_LABEL = 'REQUEST'
MSG_HEADER_CLIENT_LABEL = 'CLIENT'

REQ_CREATE_QUEUE = 'CREATE_QUEUE'
REQ_CREATE_EXCHAGE = 'CREATE_EXCHANGE'
REQ_ADD_SUBSCRIBER = 'ADD_SUBSCRIBER'
REQ_ADD_MESSGAE  = 'ADD_MESSAGE'
REQ_EXISTS_EXCHANGE = 'EXISTS_EXCHANGE'
REQ_EXISTS_QUEUE = 'EXISTS_QUEUE'

INFO_NAME_EXCHANGE = 'EXCHANGE_NAME'
INFO_TYPE_EXCHANGE = 'EXCHANGE_TYPE'
INFO_NAME_QUEUE = 'QUEUE_NAME'
INFO_NAME_SUBSCRIBER = 'SUBSCRIBER_NAME'
INFO_NAME_MESSAGE = 'PUBLISH_MESSAGE'

OPTION_ACKNOWLEDGE_LABEL = 'ACKNOWLEDGE'
OPTION_ACKNOWLEDGE_TRUE = 'TRUE'
OPTION_ACKNOWLEDGE_FALSE = 'FALSE'

TYPE_EXCHANGE_DIRECT = 'DIRECT'
TYPE_EXCHANGE_FANOUT = 'FANOUT'



